from pygame.font import SysFont, Font
from os import getcwd
from os.path import join

Comicsansms10 = SysFont("comicsansms", 10)
Comicsansms15 = SysFont("comicsansms", 15)
Comicsansms20 = SysFont("comicsansms", 20)
Comicsansms10Bold = SysFont("comicsansms", 10, bold=True)
Comicsansms15Bold = SysFont("comicsansms", 15, bold=True)
Comicsansms20Bold = SysFont("comicsansms", 20, bold=True)

Arial10 = SysFont("Arial", 10)
Arial15 = SysFont("Arial", 15)
Arial18 = SysFont("Arial", 15)
Arial20 = SysFont("Arial", 20)
Arial25 = SysFont("Arial", 25)
Arial30 = SysFont("Arial", 30)
Arial40 = SysFont("Arial", 40)
Arial50 = SysFont("Arial", 50)
Arial60 = SysFont("Arial", 60)
Arial80 = SysFont("Arial", 80)
Arial10Bold = SysFont("Arial", 10, bold=True)
Arial15Bold = SysFont("Arial", 15, bold=True)
Arial20Bold = SysFont("Arial", 20, bold=True)
Arial25Bold = SysFont("Arial", 25, bold=True)
Arial30Bold = SysFont("Arial", 30, bold=True)
Arial40Bold = SysFont("Arial", 40, bold=True)
Arial50Bold = SysFont("Arial", 50, bold=True)
Arial60Bold = SysFont("Arial", 60, bold=True)
Arial80Bold = SysFont("Arial", 80, bold=True)

Avara = Font(join(getcwd(), "assets", "CustomFont", "Avara", "Avara.ttf"),50)
Avara10 = Font(join(getcwd(), "assets", "CustomFont", "Avara", "Avara.ttf"),10)
Avara20 = Font(join(getcwd(), "assets", "CustomFont", "Avara", "Avara.ttf"),20)
Avara30 = Font(join(getcwd(), "assets", "CustomFont", "Avara", "Avara.ttf"),30)
Avara40 = Font(join(getcwd(), "assets", "CustomFont", "Avara", "Avara.ttf"),40)